# Generated by Django 5.2.4 on 2025-07-15 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timesheetentry",
            name="billing_time_duration",
            field=models.DurationField(
                default=datetime.timedelta(0), help_text="Format: HH:MM:SS"
            ),
        ),
        migrations.AlterField(
            model_name="timesheetentry",
            name="work_description",
            field=models.TextField(blank=True),
        ),
    ]
