# Generated by Django 5.2.4 on 2025-07-13 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255, unique=True)),
                ("address", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="timesheetentry",
            name="billing_consultant",
            field=models.ForeignKey(
                limit_choices_to={"role": "CONSULTANT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timesheet_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="clients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select one or more clients this user belongs to (only for Client users).",
                related_name="client_users",
                to="core.client",
            ),
        ),
    ]
