# Generated by Django 5.2.4 on 2025-07-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_timesheetentry_billing_time_duration_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["company_name"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["name"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="timesheetentry",
            options={
                "ordering": ["-date_of_service", "billing_consultant"],
                "verbose_name": "Timesheet Entry",
                "verbose_name_plural": "Timesheet Entries",
            },
        ),
        migrations.AlterUniqueTogether(
            name="timesheetentry",
            unique_together={("billing_consultant", "project", "date_of_service")},
        ),
    ]
